# Dependencies
markdown:         kramdown

# Setup
title:            Beth Watson
tagline:          'Software Developer'
description:      'Ruby. SQL. Full-Stack Web.'
url:              http://bethanyvwatson.github.io
baseurl:          ''

author:           
  name:           'Beth Watson'
  url:            http://www.bethanywatson.me

paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/bethanyvwatson/bethanyvwatson.github.io

collections:
  category:
    output: true
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
